language: cpp
compiler:
  - gcc
install:
  - cd ..
  - git clone https://github.com/mbedded-ninja/slotmachine-cpp
  - git clone https://github.com/unittest-cpp/unittest-cpp
  - "cd unittest-cpp; cmake .; make all"
  - cd ../ClideCpp
script: 
  - make